// <auto-generated />
using System;
using BookStoreService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookStoreService.Infrastructure.Migrations
{
    [DbContext(typeof(BookStoreDbContext))]
    [Migration("20240823150700_SeedLessData")]
    partial class SeedLessData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("BookStoreService.Domain.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL");

                    b.Property<int>("Sales")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1e209cbf-5175-4205-89cb-0cd33ea24987"),
                            Author = "George Orwell",
                            IsFeatured = false,
                            Price = 0m,
                            Rating = 0.0,
                            Sales = 0,
                            Stock = 0,
                            Title = "1984"
                        },
                        new
                        {
                            Id = new Guid("cfe0191a-bde6-4b6c-8bd3-d097cf557043"),
                            Author = "F. Scott Fitzgerald",
                            IsFeatured = false,
                            Price = 0m,
                            Rating = 0.0,
                            Sales = 0,
                            Stock = 0,
                            Title = "The Great Gatsby"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
